services:
  backend:
    build:
      context: .
      target: backend
    container_name: sla_backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - sla_network

  frontend:
    build:
      context: .
      target: frontend
    container_name: sla_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sla_network

networks:
  sla_network:
    driver: bridge
